language: python
python:
  - "3.6"
env:
  - DJANGO=2.1 DB=sqlite
before_install:
  - pip install pipenv
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
install:
  - pipenv install
script:
  - python manage.py test

